#!/usr/bin/env bash
set -euo pipefail

export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get install -y \
  bubblewrap \
  curl \
  fd-find \
  file \
  gawk \
  gh \
  git \
  jq \
  ripgrep \
  ruby \
  sed \
  shellcheck \
  snapd \
  tree \
  yamllint \
  wget \
  wl-clipboard \
  yq
